# Generated by Django 4.0.3 on 2022-03-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
